version: "3.9"

services:
  app_sm_tech_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_sm_tech_test
    image: sm_tech_test
    ports:
      - "8000:8000"
    networks:
      - network_sm_tech_test
    depends_on:
      - db_sm_tech_test
    restart: on-failure
    