version: "3.9"

services:
  db_sm_tech_test:
    container_name: db_sm_tech_test
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3307:${DB_PORT}"
    volumes:
      - volume_sm_tech_test:/var/lib/mysql
    networks:
      - network_sm_tech_test

volumes:
  volume_sm_tech_test:
    name: "volume_sm_tech_test"

networks:
  network_sm_tech_test:
    name: network_sm_tech_test
    driver: bridge
